### ISSUE TITLE
0.3.0: Error "No handler found [for] genGetSet.import"

### ISSUE THREAD

**Issue by TimMensch** [cybertim/vscode-gengetset#13]
I just installed the latest version and the import command doesn't fire at all for me. I just get an error suggesting that "An extension might be missing an activation event."

The getter/setter generation does work. I'm on Windows with VS Code 1.1.1.

**Comment by cybertim** [comment]
Workaround for now is using the `alt`+`shift`+`g` menu instead of triggering the import command through the command palette.
Will be fixed next update.

**Comment by cybertim** [comment]
should be fixed now (since version 0.3.1)
