### ISSUE TITLE
Add Import not working and 'No handler found for the command: 'genGetSet.import''

### ISSUE THREAD

**Issue by johan-gorter** [cybertim/vscode-gengetset#18]
On windows, I get the following error when running 'Optimze imports':

No handler found for the command: 'genGetSet.import'. An extension might be missing an activation event.

I think this happens since version 0.3.0 and it is still present in version 0.3.1

**Comment by RDalziel** [comment]
Also getting this.

**Comment by dbettini** [comment]
Happening on OSX as well. Both insiders and stable version.

**Comment by AlbertoMonteiro** [comment]
Same here.

`No handler found for the command: 'genGetSet.import'. An extension might be missing an activation event.`

Windows 10

**Comment by dbettini** [comment]
I checked the source code. I'm not sure what is happening here, but activationEvents are not even referencing existing commands. I fixed it in the package.json, but commands don't work as they should. This extension does not work at all.

**Comment by cybertim** [comment]
`genGetSet.import` is deprecated but was not yet changed to the new function name `genGetSet.sortImport` also `genGetSet.addImport` was not yet added as a seperate command.

As a workaround you can use `shift`+`alt`+`G` (the popup) and link to the `add import` and `optimize imports` from there.

**Comment by cybertim** [comment]
command (palette) naming issues are resolved in 0.3.2
