### ISSUE TITLE
Add Imports does no action

### ISSUE THREAD

**Issue by buehler** [cybertim/vscode-gengetset#21]
Hey there

When I use your plugin and I wanna `optimize imports` or `add import`, the plugin does no action at all. The constructor generator does work, but add import only shows the indexed exports. I can search through my stuff, but when I hit enter on my desired class, it just disappears.

Maybe this could be duplicated / related to #19 

Cheers

**Comment by buehler** [comment]
Hello? 😢

**Comment by cybertim** [comment]
Since it does show the Indexed Imports List it is not related to #19.
Does the `Optimize Imports` function work / do anything ?

**Comment by cybertim** [comment]
With indexed you mean the little Icon, then yes it is related to #18 
See workaround there, will be fixed next release.
