### ISSUE TITLE
Pickup quotemark style from tslint.conf

### ISSUE THREAD

**Issue by ahc-andrew** [cybertim/vscode-gengetset#23]
Extension always adds ' even when my tslint is set to "

Would be really useful if it picked it up

http://palantir.github.io/tslint/rules/quotemark/

**Comment by cybertim** [comment]
You can set the `genGetSet.pathStringDelimiter` to `"` in your vscode settings

**Comment by ahc-andrew** [comment]
Great! I would say that's a bad name though

In my head that implies if I want to use / or \ for paths.

**Comment by cybertim** [comment]
Yes the name of the setting could be cleaned up a bit, I will take this in consideration for a future update.
