### ISSUE TITLE
Honor user's formatting settings

### ISSUE THREAD

**Issue by avianbc** [cybertim/vscode-gengetset#26]
If the user has this line in his/her settings.json:

`typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = true`

then the created/optimized imports should contain spaces like:

`import { Thing } from './path';`

Notice the spaces around "Thing".

**Comment by cybertim** [comment]
added as `genGetSet.spacedImportLine`
available in version 0.3.4
