### ISSUE TITLE
Multiple Generate Getter/Setter

### ISSUE THREAD

**Issue by ronsc** [cybertim/vscode-gengetset#27]
I can generate getter/setter for multiple variable in one time ?

**Comment by cybertim** [comment]
not yet, will make this a feature for a possible next release

**Comment by ronsc** [comment]
@cybertim ok, Thank You for reply.

**Comment by dbpieter** [comment]
yes please :)

**Comment by leozhao9527** [comment]
is this in current release?

**Comment by Anexon** [comment]
I've made pull request with this improvement: [enhancement](https://github.com/cybertim/vscode-gengetset/pull/44)

**Comment by cybertim** [comment]
Added from version 0.5.0
