### ISSUE TITLE
 Add import command shows "There are no entries to pick from" if typings folder is exclude from the Eplorer #3 

### ISSUE THREAD

**Issue by letientai299** [cybertim/vscode-gengetset#28]
Thanks for greate plugins. I have a problem with `files.eclude` setting, though.
## Step to reproduce
1. In `settings.json`, eclude the `typings` folder:
   
   ``` json
   {
     "files.exclude": {
       "typings": true
     }
   }
   ```
2. Reload VS Code to make the setting applied.
3. Try `TypeScript: Add import` command. It would ask to wait for build export
   cache. Fine.
4. After some secs, try the command again. Now it's say `There are no entries to
   pick from`.

Also, remove the setting and reload vscode make the addon works again.
## Tested on
- Platform: Ubuntu 16.04
- VS Code: 1.4.0
- VS Code Insiders: 1.5.0

```
Version 1.5.0-insider
Commit 92d3324e3d05a6d2b765c08651d89e9ec1d19f4c
Date 2016-08-29T06:12:13.472Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

**Comment by cybertim** [comment]
Maybe add some more details about the project itself (folders and package.json and typings.json).
Also, typings integration is now on the deprecated list in favour of the npm @types.

**Comment by letientai299** [comment]
I'm not using vscode anymore (can't exit vim :smile:). And I'm sorry that I didn't come back in time to provide more detail on my issue. Now, I can't do anything to help but closing this issue. 

Thanks @cybertim for developing and maintaining this addon.
