### ISSUE TITLE
Should respect source settings in tsconfig

### ISSUE THREAD

**Issue by pourquoi42** [cybertim/vscode-gengetset#29]
Hi,

I would love to use this great tool but have a serious issue. "organize imports" imports hundreds of duplicate entries. Reason is that I am using a history plugin that makes copies of a file after each modification. Apparently, the toolbox does not respect the excludes that I made in .tsconfig and instead searches all my project folder for possible exports.

In any case, I think the sources settings in tsconfig must be obeyed, because I may intentionally keep some ts files somewhere in the project structure and do not want them to be active.

**Comment by cybertim** [comment]
should be fixed in v0.4.0 (by ignoring hidden directories like .history)
