### ISSUE TITLE
Import is not working

### ISSUE THREAD

**Issue by gochi-dot** [cybertim/vscode-gengetset#32]
**Code before using plugin command**

import { Component, Input, Renderer, ViewChild } from '@angular/core';

import { SimpleService } from '../services/simple.service'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements AfterViewInit{
  showed:boolean = true;
  @ViewChild('input') input;

  constructor(private renderer:Renderer) {}

  ngAfterViewInit() {
      console.log(this.input);

```
  this.renderer.setElementAttribute(
      this.input.nativeElement,
      'placeholder',
      'true'
  );
```

  }

}

`

**Code after Add Import 'AfterViewInit'**

`
import {console} from '@types/node';
import {Component, AfterViewInit, ViewChild} from '@angular/core';

import { SimpleService } from '../services/simple.service'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements AfterViewInit{
  showed:boolean = true;
  @ViewChild('input') input;

  constructor(private renderer:Renderer) {}

  ngAfterViewInit() {
      console.log(this.input);

```
  this.renderer.setElementAttribute(
      this.input.nativeElement,
      'placeholder',
      'true'
  );
```

  }

}

`

**As you see, 'Input, Renderer' was deleted, that we don't need.**

**Comment by cybertim** [comment]
could you try to use `renderer: Renderer` (notice the space after the `:`) I think this is code-style related

**Comment by gochi-dot** [comment]
@cybertim yes, thank you. And, i have another issue. Why was import {console} from '@types/node'; added ?

**Comment by cybertim** [comment]
Because there is an export called `console` in the .d file of the `@types/node` and the plugin is not very smart so there is (internally) an ignore list of common keywords for issues like this.
I will add `console` to this list in a later release.

**Comment by gochi-dot** [comment]
@cybertim thank you for the fast reply.
