### ISSUE TITLE
import from node-modules doesn't work properly

### ISSUE THREAD

**Issue by MastroLindus** [cybertim/vscode-gengetset#33]
two issues:
1)if using npm-style typings supported by typescript 2, if you try to autocomplete an import statement the resulting line will be something like import {x} from "@types/whatever" instead of import {x} from "whatever"

2)if using normal typings style, according to this https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html you can have two styles: either put the main declaration file in your root folder, or put a pointer to it under "typings" in your package.json config file. The second one works but it generates the wrong line:
in case of your declaration file being in node_modules/whatever/dist/src, instead of something like import {x} from "whatever" it will generate import {x} from "whatever/dist/src". The compiler will still be happy but obviously this is not good.

**Comment by cybertim** [comment]
should all be fixed now in v0.4.0
