### ISSUE TITLE
Does not seem to work with @types definitions

### ISSUE THREAD

**Issue by demus** [cybertim/vscode-gengetset#39]
To reproduce use the d3v4 definitely typed definitions.

`npm install @types/d3`

example typescript class where it does not work:

```
import * as d3Selection from 'd3-selection';

class Test {
  private _svgEl: d3Selection.Selection<SVGSVGElement, any, HTMLElement, any>;

}
```

**Comment by cybertim** [comment]
should work with (most) @types, so this is probably an issue related to the specific library - will look into this when I update the extension

**Comment by demus** [comment]
@cybertim It's been working recently; I may have been doing something wrong previously or had something configured incorrectly?

Either way, thanks for the package; it's increased productivity.
